alas_segitiga_siku_siku_a = input("Masukkan alas segitiga siku siku: ")
tinggi_segitiga_siku_siku_b = input("Masukkan tinggi segitiga siku siku: ")
sisi_miring_segitiga_siku_siku_c = input("Masukkan sisi miring segitiga siku siku: ")
luas_segitiga_siku_siku = 1/2 * int(alas_segitiga_siku_siku_a) * int(tinggi_segitiga_siku_siku_b) 
keliling_segitiga_siku_siku = int(alas_segitiga_siku_siku_a) + int(tinggi_segitiga_siku_siku_b) + int(sisi_miring_segitiga_siku_siku_c)
print("luas segitiga siku siku adalah", luas_segitiga_siku_siku, "Cm")
print("keliling segitiga siku siku adalah", keliling_segitiga_siku_siku, "Cm")